### ISSUE TITLE
Add cascade indicators?

### ISSUE THREAD

**Issue by tessam30** [USAID-OHA-SI/gophr#12]
Does it make sense to also have a list of cascade indicators? Was thinking this could be useful for the data viz package that will create cascade graphics?

`cascade_ind <- c("HTS_TST", "HTS_TST_POS", "TX_NEW", "TX_NET_NEW", "TX_CURR", "TX_PVLS", "TX_CURR_Lag2")`

This list would give you everything you need to calculate 90-90-90s plus linkage, VLC and VLS.

**Comment by achafetz** [comment]
Yep. And I would add `TX_PVLS_D` to the list, which is the product of `clean_indicator()`.

**Comment by tessam30** [comment]
`TX_CURR_Lag2` has been removed from the MER structured dataset as of the FY22 Q4 clean release. Should we remove this from the cascade list?
