### ISSUE TITLE
Add param to included/exclude period_type in reshape_msd

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/gophr#6]
Output of `reshape_msd` provides a new column called `period_type` to identify it as result, cumulative, or target. I probably need this column 1% of the time, so recommend a param to exclude by default but allow user to include if desired.

**Comment by baboyma** [comment]
I vote for `include by default` for backward compatibility. Thoughts?

**Comment by achafetz** [comment]
I hear you. Is it something you use in your scripts?

If the default were sent to exclude going forward by default, what about including an warning message?
```
Warning: Dropping period_type from dataframe, which was included in earlier versions of `reshape_msd()`. If you need this column for backwards compatibility, add `include_type = FALSE` in `reshape_msd()`
```

**Comment by baboyma** [comment]
Works for me.
